version: "2.23"

services:
  database:
    image: postgres
    container_name: my_database

    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/18/docker

  backend:
    image: backend
    container_name: my_backend
    ports:
      - "3000:3000"
    depends_on:
      database:
        condition: service_healthy

    environment:
      DATABASE_URL: "${DATABASE_URL}"

volumes:
  postgres_data:
